services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/conf/generated:/etc/nginx/conf.d
      - ./services/nginx/conf/gateway.conf:/etc/nginx/conf.d/gateway.conf
      - ./services/nginx/mediafiles:/static:ro
      - ./services/nginx/staticfiles:/static:ro
      - ./utils/nginx_snippets/generated/:/etc/nginx/snippets
      - ./utils/certbot/conf/:/etc/letsencrypt
      - ./utils/certbot/www/:/var/www/certbot/
    env_file:
      - ./services/tandoor/.env
    networks:
      - gateway
      - main
  mediatracker:
    image: bonukai/mediatracker:latest
    restart: "unless-stopped"
    container_name: mediatracker
    expose:
      - 7481
    volumes:
      - ./services/mediatracker/data:/storage
      - mediatracker_assets:/assets
    networks:
      - main
  jellyseerr:
    image: fallenbagel/jellyseerr
    restart: "unless-stopped"
    container_name: jellyseerr_req_man
    expose:
      - "5055"
    volumes:
      - ./services/jellyseerr/config:/app/config
    networks:
      - main
  organizr:
    image: organizr/organizr:latest
    container_name: organizr_dash
    volumes:
      - ./services/organizr/config:/config
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - main
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer-docker-ui-server
    expose:
      - "9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/portainer/data:/data
    networks:
      - main
  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    ports:
      - 8080:8080
    environment:
      {
        "APACHE_PORT": 11000,
        "APACHE_IP_BINDING": 0.0.0.0,
        "SKIP_DOMAIN_VALIDATION": true,
        "NEXTCLOUD_DATADIR": "/Users/gabe/homiehub-homelab/data/drive",
        "NEXTCLOUD_MOUNT": "/Users/gabe/homiehub-homelab/data",
      }
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock.raw:/var/run/docker.sock:ro
    networks:
      - main
  tandoor_db:
    restart: always
    image: postgres:16-alpine
    container_name: tandoor_recipes_postgres_db
    volumes:
      - ./services/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./services/tandoor/.env
    networks:
      - main
  tandoor_webserver:
    restart: always
    image: vabene1111/recipes
    container_name: tandoor_recipes_webserver
    expose:
      - "8080"
    env_file:
      - ./services/tandoor/.env
    volumes:
      - ./services/tandoor/staticfiles:/opt/recipes/staticfiles
      - ./services/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_db
    networks:
      - main
  freshrss_aggregator:
    restart: unless-stopped
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    volumes:
      - ./services/freshrss/config:/config
    expose:
      - "80"
    networks:
      - main

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  mediatracker_assets:
    name: mediatracker_assets
networks:
  main:
  gateway:
    external: true
