- name: Initialize local environment
  hosts: localhost

  vars_prompt:
    - name: domain
      prompt: "What domain will you be using? If this is a development environment, please use the domain 'localhost' with no apostrophes exactly."
      private: no
    - name: cloudflare_api_token
      prompt: "What is your Cloudflare API token? Make sure the permissions for the token are set correctly according to certbot-dns-cloudflare's requirements."
    - name: python_interpreter_path
      prompt: "What is the absolute path to your Python interpreter? If unsure, run 'which python' from inside your virtual environment and copy the result here."
      private: no
    - name: tandoor_db_password
      prompt: "What password would you like to use for the Postgres DB supporting your Tandoor instance?"
    - name: tandoor_db_secret_key
      prompt: "What secret key would you like to use for your Tandoor instance?"

  tasks:
    - name: Create a local inventory.yml file if it doesn't already exist
      ansible.builtin.template:
        src: "../inventory.yml.j2"
        dest: "../inventory.yml"
        mode: "0644"
