- name: Set up and start dev environment locally
  hosts: localhost

  tasks:
    - name: Start up leantime instance
      community.docker.docker_compose_v2:
        project_src: "${PWD}/../services/leantime"

    - name: Start up dev app
      community.docker.docker_compose_v2:
        project_src: "${PWD}/../"
        files:
          - "docker-compose.core.yml"
